# Generated by Django 3.0.3 on 2020-03-03 14:14

from django.db import migrations, models
import lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200303_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[lib.validators.validate_user_code_in_list], verbose_name='employee code'),
        ),
    ]
